version: '3.8'

volumes:
  redis:
    driver: ${DRIVER_VOLUMES}

services:
  redis:
    image: nuldark/redis:${REDIS_VERSION}
    command: --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:delegated
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend