version: '3.8'

services:
  nginx:
    build: 
      context: nginx/
      args:
        - NGINX_VERSION=${NGINX_VERSION}

  postgres:
    build:
      context: postgres/
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
  
  redis:
    build:
      context: redis/
      args:
        - REDIS_VERSION=${REDIS_VERSION}