version: '3.8'

networks:
  backend:
    external: true
    driver: ${NETWORKS_DRIVER}
  frontend:
    external: true
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  nginx:
    image: ghcr.io/bytebits9/nginx:latest
    volumes:
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available/
      - ${PLATFORM_CODE_PATH_HOST}:${PLATFORM_CODE_PATH_CONTAINER}
    ports:
      - "80:80"
      - "433:433"
    networks:
      - backend
      - frontend

  redis:
    image: ghcr.io/bytebits9/redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    image: ghcr.io/bytebits9/postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend