version: '3.8'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
  frontend:
    driver: ${NETWORKS_DRIVER}

volumes:
  docker-in-docker:
    driver: ${DRIVER_VOLUMES}

services:
  php-fpm:
    build:
      context: ./docker/php/
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${APP_HOST_PATH}:${APP_CONTAINER_PATH}${APP_CONTAINER_FLAG}
      - ./docker/php/php-fpm/www.conf:/usr/local/etc/php/php-fpm.d/www.conf:delegated
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend

  nginx:
    image: nuldark/nginx:${NGINX_VERSION}
    volumes:
      - ${APP_HOST_PATH}:${APP_CONTAINER_PATH}${APP_CONTAINER_FLAG}
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:delegated
      - ./docker/nginx/ssl:/etc/nginx/ssl:delegated
    ports:
      - "${NGINX_HOST_PORT_HTTP}:80"
      - "${NGINX_HOST_PORT_HTTPS}:433"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  mailhog:
    image: mailhog/mailhog:${MAILHOG_VERSION}
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_HTTP_PORT}:8025"
    networks:
      - frontend
      - backend