version: '3.8'

networks:
  backend:
    driver: ${DRIVER_NETWORKS}
  frontend:
    driver: ${DRIVER_NETWORKS}

volumes:
  postgres:
    driver: ${DRIVER_VOLUMES}
  redis:
    driver: ${DRIVER_VOLUMES}

services:
  php-fpm:
    image: ghcr.io/nulldark/php-fpm:latest
    volumes:
      - ./.docker/php-fpm/www.conf:/etc/php/${PHP_VERSION}/php-fpm.d/www.conf
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${LOGS_PATH_HOST}/php-fpm:/var/log/php-fpm
    networks:
      - backend
    expose:
      - "9000"

  nginx:
    image: ghcr.io/nulldark/nginx:${NGINX_VERSION}
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${LOGS_PATH_HOST}/nginx:/var/log/nginx
      - ${NGINX_HOST_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_HOST_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_PORT_HTTP}:80"
      - "${NGINX_HOST_PORT_HTTPS}:433"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  redis:
    image: redis:${REDIS_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend