version: '3.8'

services:
  mail:
    image: mailhog/mailhog:${MAILHOG_VERSION}
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_HTTP_PORT}:8025"
    networks:
      - frontend
      - backend