name: CI

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        services: [ 'nginx', 'redis', 'postgres' ]

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkoout
        uses: actions/checkout@v4
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.services }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.services }}:${{ github.run_id }}, \
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.services }}:latest